name = "Omega"
uuid = "1af16e33-887a-59b3-8344-18f1671b3ade"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.1"

[compat]
julia = "1"

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Spec = "b8ccf107-3a88-5e0f-823b-b838c6a0f327"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Spec", "Test", "Pkg", "InteractiveUtils"]
